services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    container_name: hono-backend
    ports:
      - "${BACKEND_PORT}:3000" 
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    container_name: react-frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env

