services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: hono-backend
    ports:
      - "${BACKEND_PORT}:3000" 
    env_file:
      - .env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: react-frontend
    ports:
      - "80:80"
    env_file:
      - .env

